version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      REPO_OWNER: ${REPO_OWNER}
      REPO_NAME: ${REPO_NAME}
      FILE_PATH: ${FILE_PATH}
      BRANCH: ${BRANCH}
      GROQ_API_KEY: ${GROQ_API_KEY}
    volumes:
      - .:/app
    restart: always
